stages:
    - name: Publish
      steps:
          - publishImageConfig:
                dockerfilePath: ./Dockerfile
                buildContext: .
                tag: naviapp-webapp:${CICD_EXECUTION_SEQUENCE}
      when:
          branch: master
          event: [push, pull_request]
    - name: Deploy
      steps:
          - applyYamlConfig:
                path: ./deployment.yml
notification: {}
