stages:
    - name: Publish
      steps:
          - publishImageConfig:
                dockerfilePath: ./Dockerfile
                buildContext: .
                tag: naviapp-webapp:${CICD_EXECUTION_SEQUENCE}
      when:
          branch:
              include:
                  - master
          event: {}
    - name: Deploy
      steps:
          - applyYamlConfig:
                path: ./deployment.yml
notification: {}
